name: packagekit
version: 0.2.1

description:
  Provides a client to connect to PackageKit - the service that enables installation and removal of software packages on Linux.

homepage: https://github.com/canonical/packagekit.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  dbus: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
  test_cov: ^1.0.1

