name: packagekit
version: 0.1.1

description:
  Provides a client to connect to PackageKit - the service that enables installation and removal of software packages on Linux.

homepage: https://github.com/canonical/packagekit.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.6.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  test_cov: ^1.0.1

