name: packagekit
version: 0.1.0

description:
  Provides a client to connect to PackageKit - the service that enables installation and removal of software packages on Linux.

homepage: https://github.com/canonical/packagekit.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
